#!/bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=4000Mb
#PBS -t 1-34
#PBS -d /storage/home/ssobie/code/repos/downscale_CMIP6/
#PBS -o ./out_files/CanESM5-tasmax-r8i1p2f1-qdrank.out
#PBS -e ./out_files/CanESM5-tasmax-r8i1p2f1-qdrank.err
#PBS -N qd.tx.can.r8i

cd /storage/home/ssobie/code/repos/downscale_CMIP6/
echo "Current working directory is `pwd`"

gcm="CanESM5"
run="r8i1p2f1"
scenario="ssp126"

varname="tasmax"
obsdir="/storage/data/climate/observations/gridded/ANUSPLIN/ANUSPLIN_300ARCSEC/anusplin_tasmax_split/"
bccidir="/storage/data/climate/downscale/BCCAQ2/BCCI/tasmax_CanESM5_r8i1p2f1_ssp126_split15/"
bccadir="/storage/data/climate/downscale/BCCAQ2/BCCA/"
bccafile="CanESM5.tasmax.ssp126.r8i1p2f1.Canada.analogues.RData"
writedir="/storage/data/climate/downscale/BCCAQ2/raw_downscaled/ds_tasmax_CanESM5_r8i1p2f1_ssp126_split15/"

obsfile=$(find $obsdir -maxdepth 1 -type f -name "anusplin_"$varname'*.nc' -execdir basename {} \; | sort | sed -n ${PBS_ARRAYID}p)
bccifile=$(find $bccidir -maxdepth 1 -type f -name $varname'*.nc' -execdir basename {} \; | sort | sed -n ${PBS_ARRAYID}p)

echo $obsfile
echo $bccifile

R CMD BATCH --no-restore --no-save "--args tmpdir='$TMPDIR' varname='$varname' gcm='$gcm' run='$run' scenario='$scenario' obsfile='$obsfile' obsdir='$obsdir' bccidir='$bccidir' bccifile='$bccifile' bccadir='$bccadir' bccafile='$bccafile' writedir='$writedir'" qdm.and.rank.r "./out_files/${gcm}.${varname}.${scenario}.${run}.qdm.and.rank.${PBS_ARRAYID}.out"
