#!/bin/bash
#PBS -l walltime=12:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=10000Mb
#PBS -d /storage/home/ssobie/code/repos/downscale_CMIP6/
#PBS -o output=./out_files/CanESM5-tasmax-r2i1p2f1-bcci.out
#PBS -e error=./out_files/CanESM5-tasmax-r2i1p2f1-bcci.err
#PBS -N bcci.can.r2i


cd /storage/home/ssobie/code/repos/downscale_CMIP6/
echo "Current working directory is `pwd`"

gcm="CanESM5"
run="r2i1p2f1"
scenario="ssp585"

varname="tasmax"
gcmfile="tasmax_day_CanESM5_North_America_historical+ssp585_r2i1p2f1_gn_19500101-21001231.nc"
gcmdir="/storage/data/climate/CMIP6/assembled/CanESM5/north_america/"
obsfile="anusplin_tasmax_final.nc"
obsdir="/storage/data/climate/observations/gridded/ANUSPLIN/ANUSPLIN_300ARCSEC/"
bccifile="tasmax_BCCI_day_CanESM5_North_America_historical+ssp585_r2i1p2f1_gn_19500101-21001231.nc"
writedir="/storage/data/climate/downscale/BCCAQ2/BCCI/"

R CMD BATCH "--args tmpdir='/local_temp/ssobie/' varname='$varname' gcmfile='$gcmfile' gcmdir='$gcmdir' obsfile='$obsfile' obsdir='$obsdir' bccifile='$bccifile' writedir='$writedir'" bcci.and.divide.r "./${gcm}.${varname}.${scenario}.${run}.bcci.out"
